export TIMETABLE_BOT_USERNAME="{student number}"
export TIMETABLE_BOT_PASSWORD="{timetable password}"
export TIMETABLE_BOT_SUBJECT="{subject code}"
export TIMETABLE_BOT_CLASS_TYPE="{class type}"
export TIMETABLE_BOT_ACTIVITY_CODES="{class activity codes as comma separated list}"
export TIMETABLE_BOT_TO_EMAIL="{notify email address}"
export TIMETABLE_BOT_PING_FREQUENCY="10"  # Optional value to set a ping frequency.
export GMAIL_USERNAME="{sender email address}"
export GMAIL_PASSWORD="{sender email password}"
export GMAIL_SMTP_SERVER="smtp.gmail.com"   # Change smtp server details if using another email provider.
export GMAIL_SMTP_SERVER_PORT="587"
